from setuptools import setup

#TODO add classifiers
setup(name="serrec_validator",
        version="0.1",
        url='https://github.com/AyoubMKDM/SerRec-Validator',
        description="Simplify, help building, and benchmarking service recommender models",
        packages=setup.find_packages(),
        author="Ayoub Mokeddem",
        author_email="ayoubmkdm3@gmail.com",
        install_requires=["numpy",
                            "pandas",
                            "surprise"],
        include_package_data=True,
        package_data={'':['wsdream/*.txt']},
        classifiers=[
            'Programming Language :: Python',
            'Programming Language :: Python :: 3',
            'Programming Language :: Python :: 3.8',
            'Intended Audience :: Science/Research',
            'Intended Audience :: Developers',
            'Intended Audience :: Education',
            'Intended Audience :: Information Technology',
            'Operating System :: OS Independent',
            'Topic :: Scientific/Engineering',
            'Topic :: Scientific/Engineering :: Artificial Intelligence',
            'Topic :: System :: Benchmark',
        ],
        python_requires=">=3.8",
        )